name: Release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v7
      name: Checkout repository

    - uses: actions/setup-python@v7
      with:
        python-version: "3.12"

    - name: uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install build tooling
      run: uv pip install --group release --system

    - name: Build wheel and source tarball
      run: python3 -m build

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/
        if-no-files-found: error

  publish:
    needs: [build]
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyerrors
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Sanity check
        run: ls -la dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
